# Generated by Django 2.1.4 on 2019-02-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FunctionalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.ImageField(null=True, upload_to='product_logos/')),
                ('buyer_personals', models.ManyToManyField(to='products.BuyerPersonal')),
                ('functional_categories', models.ManyToManyField(to='products.FunctionalCategory')),
                ('key_words', models.ManyToManyField(to='products.KeyWord')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeatureFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='product_feature_files/')),
                ('functional_categories', models.ManyToManyField(to='products.FunctionalCategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_feature_files', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductHyperlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=255)),
                ('functional_categories', models.ManyToManyField(to='products.FunctionalCategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_hyperlinks', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPitchDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='product_pitchdeck_files/')),
                ('functional_categories', models.ManyToManyField(to='products.FunctionalCategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_pitchdeck_files', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='UserPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='productpitchdeck',
            name='verticals',
            field=models.ManyToManyField(to='products.Vertical'),
        ),
        migrations.AddField(
            model_name='producthyperlink',
            name='verticals',
            field=models.ManyToManyField(to='products.Vertical'),
        ),
        migrations.AddField(
            model_name='productfeaturefile',
            name='verticals',
            field=models.ManyToManyField(to='products.Vertical'),
        ),
    ]
