# Generated by Django 2.1.4 on 2019-02-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='company_profile_pics/'),
        ),
    ]
