# Generated by Django 2.1.4 on 2019-02-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='teams',
            field=models.ManyToManyField(to='users.Department'),
        ),
        migrations.AddField(
            model_name='product',
            name='user_personals',
            field=models.ManyToManyField(to='products.UserPersonal'),
        ),
        migrations.AddField(
            model_name='product',
            name='verticals',
            field=models.ManyToManyField(to='products.Vertical'),
        ),
    ]
